"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { registerClockIn, registerClockOut, requestLeave, updateLeaveStatus } from "@/actions/hr";
import type { LeaveStatus, LeaveType } from "@/lib/types/database.types";

type Attendance = { id: string; clock_in: string; clock_out: string | null };
type Leave = { id: string; type: LeaveType; start_date: string; end_date: string; status: LeaveStatus; user_id: string };

export function HrWorkspace({ attendance, leaves, canApprove }: { attendance: Attendance[]; leaves: Leave[]; canApprove: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  function run(action: Promise<{ success: boolean; error?: string }>) { startTransition(async () => { const result = await action; setMessage(result.success ? "Cambios guardados." : result.error ?? "No se pudo guardar."); if (result.success) router.refresh(); }); }
  const openAttendance = attendance.some((item) => !item.clock_out);
  return <div className="space-y-8"><div className="flex flex-wrap gap-3"><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold disabled:opacity-50" disabled={isPending || openAttendance} onClick={() => run(registerClockIn())} type="button">Registrar entrada</button><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={isPending || !openAttendance} onClick={() => run(registerClockOut())} type="button">Registrar salida</button></div>{message ? <p className="text-sm text-slate-600">{message}</p> : null}<section><h2 className="mb-4 text-xl font-semibold">Mi asistencia de hoy</h2>{attendance.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay fichajes registrados hoy.</div> : <div className="space-y-3">{attendance.map((item) => <div className="rounded-2xl border border-slate-200 bg-white p-5" key={item.id}>Entrada: {new Date(item.clock_in).toLocaleString("es-ES")} · Salida: {item.clock_out ? new Date(item.clock_out).toLocaleString("es-ES") : "Abierta"}</div>)}</div>}</section><section><h2 className="mb-4 text-xl font-semibold">Solicitudes de ausencia</h2>{leaves.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay solicitudes. Crea la primera.</div> : <div className="space-y-3">{leaves.map((leave) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5" key={leave.id}><div><p className="font-semibold">{leave.type}</p><p className="text-sm text-slate-500">{leave.start_date} a {leave.end_date}</p></div>{canApprove ? <select className="rounded-lg border px-3 py-2 text-sm" disabled={isPending} onChange={(event) => run(updateLeaveStatus(leave.id, event.target.value as LeaveStatus))} value={leave.status}><option value="pendiente">Pendiente</option><option value="aprobado">Aprobado</option><option value="rechazado">Rechazado</option></select> : <span className="text-sm">{leave.status}</span>}</div>)}</div>}<form className="mt-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(requestLeave({ type: form.get("type") as LeaveType, startDate: String(form.get("startDate")), endDate: String(form.get("endDate")) })); }}><select className="rounded-lg border px-3 py-2" name="type"><option value="vacaciones">Vacaciones</option><option value="baja_medica">Baja médica</option><option value="personal">Personal</option></select><input className="rounded-lg border px-3 py-2" name="startDate" type="date" required /><input className="rounded-lg border px-3 py-2" name="endDate" type="date" required /><button className="rounded-lg bg-slate-950 px-4 py-2 text-white" disabled={isPending} type="submit">Solicitar</button></form></section></div>;
}
