"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { createProduct, updateStock } from "@/actions/inventory";
import type { MovementType } from "@/lib/types/database.types";

type Product = { id: string; sku: string; name: string; description: string | null; price: number; stock_quantity: number; min_stock_alert: number; category_id: string | null };
type Category = { id: string; name: string };

export function InventoryWorkspace({ products, categories }: { products: Product[]; categories: Category[] }) {
  const router = useRouter(); const [showProductForm, setShowProductForm] = useState(false); const [selected, setSelected] = useState<Product | null>(null); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  function refresh(action: Promise<{ success: boolean; error?: string }>) { startTransition(async () => { const result = await action; setMessage(result.success ? "Cambios guardados." : result.error ?? "No se pudo guardar."); if (result.success) { setShowProductForm(false); setSelected(null); router.refresh(); } }); }
  return <div className="space-y-6"><div className="flex flex-wrap justify-end gap-3"><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold" onClick={() => setShowProductForm(true)} type="button">Nuevo producto</button></div>{message ? <p className="text-sm text-slate-600">{message}</p> : null}{products.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay productos registrados. Crea el primero para comenzar.</div> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-6 py-4">SKU</th><th className="px-6 py-4">Producto</th><th className="px-6 py-4">Precio</th><th className="px-6 py-4">Stock</th><th className="px-6 py-4">Acción</th></tr></thead><tbody className="divide-y divide-slate-100">{products.map((product) => { const low = product.stock_quantity <= product.min_stock_alert; return <tr key={product.id}><td className="px-6 py-4 font-mono text-xs">{product.sku}</td><td className="px-6 py-4 font-medium">{product.name}</td><td className="px-6 py-4">€{Number(product.price).toFixed(2)}</td><td className={`px-6 py-4 font-semibold ${low ? "text-rose-600" : "text-emerald-600"}`}>{product.stock_quantity}{low ? " · Bajo" : ""}</td><td className="px-6 py-4"><button className="rounded-lg border px-3 py-2 text-xs" onClick={() => setSelected(product)} type="button">Ajustar stock</button></td></tr>; })}</tbody></table></div>}
    {showProductForm ? <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-950/40 p-6"><form className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); refresh(createProduct({ sku: String(form.get("sku")), name: String(form.get("name")), price: Number(form.get("price")), cost: Number(form.get("cost")), minStockAlert: Number(form.get("minStockAlert")), categoryId: String(form.get("categoryId")) || null })); }}><h2 className="text-xl font-semibold">Nuevo producto</h2><input className="w-full rounded-lg border p-3" name="sku" placeholder="SKU" required /><input className="w-full rounded-lg border p-3" name="name" placeholder="Nombre" required /><select className="w-full rounded-lg border p-3" name="categoryId"><option value="">Sin categoría</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input className="w-full rounded-lg border p-3" name="price" placeholder="Precio" type="number" step="0.01" min="0" required /><input className="w-full rounded-lg border p-3" name="cost" placeholder="Coste" type="number" step="0.01" min="0" required /><input className="w-full rounded-lg border p-3" name="minStockAlert" placeholder="Alerta mínima" type="number" min="0" required /><div className="flex justify-end gap-2"><button className="rounded-lg border px-4 py-2" onClick={() => setShowProductForm(false)} type="button">Cancelar</button><button className="rounded-lg bg-slate-950 px-4 py-2 text-white" disabled={isPending} type="submit">Guardar</button></div></form></div> : null}
    {selected ? <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-950/40 p-6"><form className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); refresh(updateStock(selected.id, Number(form.get("quantity")), form.get("type") as MovementType, String(form.get("reason")))); }}><h2 className="text-xl font-semibold">Ajustar {selected.name}</h2><select className="w-full rounded-lg border p-3" name="type"><option value="entrada">Entrada</option><option value="salida">Salida</option><option value="ajuste">Ajuste</option></select><input className="w-full rounded-lg border p-3" name="quantity" min="1" placeholder="Cantidad" type="number" required /><input className="w-full rounded-lg border p-3" name="reason" placeholder="Motivo" /><div className="flex justify-end gap-2"><button className="rounded-lg border px-4 py-2" onClick={() => setSelected(null)} type="button">Cancelar</button><button className="rounded-lg bg-slate-950 px-4 py-2 text-white" disabled={isPending} type="submit">Guardar</button></div></form></div> : null}
  </div>;
}
