"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { createCampaign } from "@/actions/enterprise";
import type { CampaignStatus } from "@/lib/types/database.types";

type Campaign = { id: string; name: string; budget: number; platform: string; status: CampaignStatus };
type Performance = { id: string; campaign_id: string; leads_count: number; conversions_count: number; spend: number; measured_at: string };

export function MarketingWorkspace({ campaigns, performance }: { campaigns: Campaign[]; performance: Performance[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await createCampaign({ name: String(form.get("name")), platform: String(form.get("platform")), budget: Number(form.get("budget")), status: form.get("status") as CampaignStatus }); setMessage(result.success ? "Campaña creada." : result.error ?? "No se pudo crear."); if (result.success) { setOpen(false); router.refresh(); } }); }
  return <div className="space-y-6"><div className="flex justify-end"><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold" onClick={() => setOpen(true)} type="button">Nueva campaña</button></div>{message ? <p className="text-sm text-slate-600">{message}</p> : null}{campaigns.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay campañas registradas. Crea la primera.</div> : <div className="grid gap-5 md:grid-cols-2">{campaigns.map((campaign) => { const stats = performance.filter((item) => item.campaign_id === campaign.id).reduce((sum, item) => ({ leads: sum.leads + item.leads_count, conversions: sum.conversions + item.conversions_count, spend: sum.spend + Number(item.spend) }), { leads: 0, conversions: 0, spend: 0 }); return <article className="rounded-2xl border border-slate-200 bg-white p-6" key={campaign.id}><div className="flex justify-between gap-3"><h2 className="font-semibold">{campaign.name}</h2><span className="text-sm text-slate-500">{campaign.status}</span></div><p className="mt-2 text-sm text-slate-500">{campaign.platform} · Presupuesto €{Number(campaign.budget).toFixed(2)}</p><div className="mt-5 grid grid-cols-3 gap-3 text-center text-sm"><div><p className="text-xl font-semibold">{stats.leads}</p><p className="text-slate-500">Leads</p></div><div><p className="text-xl font-semibold">{stats.conversions}</p><p className="text-slate-500">Conversiones</p></div><div><p className="text-xl font-semibold">€{stats.spend.toFixed(2)}</p><p className="text-slate-500">Inversión</p></div></div></article>; })}</div>}{open ? <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-950/40 p-6"><form className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6" onSubmit={submit}><h2 className="text-xl font-semibold">Nueva campaña</h2><input className="w-full rounded-lg border p-3" name="name" placeholder="Nombre" required /><input className="w-full rounded-lg border p-3" name="platform" placeholder="Plataforma" required /><input className="w-full rounded-lg border p-3" name="budget" min="0" placeholder="Presupuesto" step="0.01" type="number" required /><select className="w-full rounded-lg border p-3" name="status"><option value="borrador">Borrador</option><option value="activa">Activa</option><option value="pausada">Pausada</option></select><div className="flex justify-end gap-2"><button className="rounded-lg border px-4 py-2" onClick={() => setOpen(false)} type="button">Cancelar</button><button className="rounded-lg bg-slate-950 px-4 py-2 text-white" disabled={isPending} type="submit">Guardar</button></div></form></div> : null}</div>;
}
