"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import { createProject, updateTaskStatus } from "@/actions/ops";
import type { ProjectStatus, TaskStatus } from "@/lib/types/database.types";

type Project = { id: string; name: string; description: string | null; status: ProjectStatus };
type Task = { id: string; project_id: string; title: string; status: TaskStatus; priority: string; due_date: string | null };
const statuses: TaskStatus[] = ["pendiente", "en_progreso", "revision", "completado"];

export function OperationsWorkspace({ projects, tasks }: { projects: Project[]; tasks: Task[] }) {
  const router = useRouter(); const [showProjectForm, setShowProjectForm] = useState(false); const [message, setMessage] = useState(""); const [isPending, startTransition] = useTransition();
  function refresh(action: Promise<{ success: boolean; error?: string }>) { startTransition(async () => { const result = await action; setMessage(result.success ? "Cambios guardados." : result.error ?? "No se pudo guardar."); if (result.success) { setShowProjectForm(false); router.refresh(); } }); }
  return <div className="space-y-8"><div className="flex justify-end"><button className="rounded-xl bg-cyan-300 px-4 py-2.5 text-sm font-semibold" onClick={() => setShowProjectForm(true)} type="button">Nuevo proyecto</button></div>{message ? <p className="text-sm text-slate-600">{message}</p> : null}{projects.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay proyectos. Crea el primero para organizar el trabajo.</div> : <div className="grid gap-5 md:grid-cols-2">{projects.map((project) => { const projectTasks = tasks.filter((task) => task.project_id === project.id); const completed = projectTasks.filter((task) => task.status === "completado").length; const progress = projectTasks.length ? Math.round((completed / projectTasks.length) * 100) : 0; return <article className="rounded-2xl border border-slate-200 bg-white p-6" key={project.id}><div className="flex justify-between gap-3"><h2 className="font-semibold">{project.name}</h2><span className="text-xs text-slate-500">{project.status}</span></div><p className="mt-2 text-sm text-slate-500">{project.description ?? "Sin descripción"}</p><div className="mt-5"><div className="mb-2 flex justify-between text-xs text-slate-500"><span>Progreso</span><span>{progress}%</span></div><div className="h-2 rounded-full bg-slate-200"><div className="h-2 rounded-full bg-cyan-400" style={{ width: `${progress}%` }} /></div></div></article>; })}</div>}
    <section><h2 className="mb-4 text-xl font-semibold">Tareas</h2>{tasks.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No hay tareas registradas.</div> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{statuses.map((status) => <div className="rounded-2xl bg-slate-200/60 p-4" key={status}><h3 className="mb-3 text-sm font-semibold uppercase text-slate-600">{status}</h3><div className="space-y-3">{tasks.filter((task) => task.status === status).map((task) => <div className="rounded-xl bg-white p-4 shadow-sm" key={task.id}><p className="font-medium">{task.title}</p><p className="mt-1 text-xs text-slate-500">Prioridad: {task.priority}</p><select className="mt-3 w-full rounded-lg border px-2 py-1 text-xs" disabled={isPending} onChange={(event) => refresh(updateTaskStatus(task.id, event.target.value as TaskStatus))} value={task.status}>{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select></div>)}</div></div>)}</div>}</section>{showProjectForm ? <div className="fixed inset-0 z-10 flex items-center justify-center bg-slate-950/40 p-6"><form className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); refresh(createProject({ name: String(form.get("name")), description: String(form.get("description")) })); }}><h2 className="text-xl font-semibold">Nuevo proyecto</h2><input className="w-full rounded-lg border p-3" name="name" placeholder="Nombre" required /><textarea className="w-full rounded-lg border p-3" name="description" placeholder="Descripción" /><div className="flex justify-end gap-2"><button className="rounded-lg border px-4 py-2" onClick={() => setShowProjectForm(false)} type="button">Cancelar</button><button className="rounded-lg bg-slate-950 px-4 py-2 text-white" disabled={isPending} type="submit">Guardar</button></div></form></div> : null}</div>;
}
